package IreneSolutions;

import com.google.gson.GsonBuilder;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpClient;

import java.util.logging.Level;
import java.util.logging.Logger;

import com.google.gson.Gson;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.PrintStream;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.printing.PDFPageable;

/**
 *
 * @author ivan
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/copiluz.png")).getImage());
        LocalDate fechaActual = LocalDate.now();
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("MM/yyyy");
        String formatoMesYAnio = fechaActual.format(formateador);
        Serie.setText(formatoMesYAnio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NumeroFactura = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        clientearea = new javax.swing.JLabel();
        cif = new javax.swing.JLabel();
        codigocliente = new javax.swing.JLabel();
        clientedireccion = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Serie = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Empresa = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        Descripcion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        BotonImprimir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        liva = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Importe = new javax.swing.JLabel();
        Iva = new javax.swing.JLabel();
        ImporteTotal = new javax.swing.JLabel();
        TipoFactura1 = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        jLabel6.setText("Importe total");

        jTextField6.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Copiadoras Costaluz Facturas");
        setBackground(new java.awt.Color(0, 0, 102));
        setForeground(java.awt.Color.darkGray);
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Numero Factura");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 56, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 78, 89, -1));

        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("Nombre Cliente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 28, -1, -1));

        jLabel8.setForeground(new java.awt.Color(51, 0, 153));
        jLabel8.setText("Nif Cliente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 84, 87, -1));

        jLabel9.setForeground(new java.awt.Color(51, 0, 153));
        jLabel9.setText("Codigo Cliente");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 56, 87, -1));

        jLabel10.setForeground(new java.awt.Color(51, 0, 153));
        jLabel10.setText("direccion");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 118, 87, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 28, -1, -1));

        NumeroFactura.setBackground(new java.awt.Color(0, 102, 255));
        NumeroFactura.setForeground(new java.awt.Color(0, 51, 204));
        NumeroFactura.setText("jLabel11");
        getContentPane().add(NumeroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 89, -1));

        Fecha.setBackground(new java.awt.Color(0, 102, 255));
        Fecha.setForeground(new java.awt.Color(0, 51, 204));
        Fecha.setText("jLabel11");
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 78, 89, -1));

        clientearea.setBackground(new java.awt.Color(0, 102, 255));
        clientearea.setForeground(new java.awt.Color(0, 51, 204));
        clientearea.setText("jLabel11");
        getContentPane().add(clientearea, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 28, 209, -1));

        cif.setBackground(new java.awt.Color(0, 102, 255));
        cif.setForeground(new java.awt.Color(0, 51, 204));
        cif.setText("jLabel11");
        getContentPane().add(cif, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 84, 142, -1));

        codigocliente.setBackground(new java.awt.Color(0, 102, 255));
        codigocliente.setForeground(new java.awt.Color(0, 51, 204));
        codigocliente.setText("jLabel11");
        getContentPane().add(codigocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 56, 209, -1));

        clientedireccion.setBackground(new java.awt.Color(0, 102, 255));
        clientedireccion.setForeground(new java.awt.Color(0, 51, 204));
        clientedireccion.setText("jLabel11");
        getContentPane().add(clientedireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 118, 301, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Serie");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 28, 89, -1));

        Serie.setForeground(new java.awt.Color(0, 102, 255));
        getContentPane().add(Serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 28, 89, 16));

        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Tipo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 105, -1, -1));

        Empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "copiadoras costaluz", "asitecsur", " " }));
        getContentPane().add(Empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 242, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Descripcion");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 157, -1, -1));
        getContentPane().add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 151, 242, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        BotonImprimir.setText("Enviar");
        BotonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(BotonImprimir)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar)
                            .addComponent(BotonImprimir))
                        .addGap(16, 16, 16))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 920, 130));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setForeground(new java.awt.Color(51, 0, 153));
        jLabel5.setText("Importe total");

        liva.setForeground(new java.awt.Color(51, 0, 153));
        liva.setText("IVA");

        jLabel3.setForeground(new java.awt.Color(51, 0, 153));
        jLabel3.setText("Importe");

        Importe.setBackground(new java.awt.Color(0, 102, 255));
        Importe.setForeground(new java.awt.Color(0, 51, 204));
        Importe.setText("jLabel11");

        Iva.setBackground(new java.awt.Color(0, 102, 255));
        Iva.setForeground(new java.awt.Color(0, 51, 204));
        Iva.setText("jLabel11");

        ImporteTotal.setBackground(new java.awt.Color(0, 102, 255));
        ImporteTotal.setForeground(new java.awt.Color(0, 51, 204));
        ImporteTotal.setText("jLabel11");
        ImporteTotal.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(518, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liva, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Importe, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Iva, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Importe))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liva)
                    .addComponent(Iva))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ImporteTotal))
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 920, 150));

        TipoFactura1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F1", "F2", "R1", "R2", "R3", "R4", "R5", "F3", " " }));
        getContentPane().add(TipoFactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 100, 242, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImprimirActionPerformed

        try {

            JsonEnvio jSon = new JsonEnvio();

            jSon.setServiceKey("aXZhbkBjb3BpYWRvcmFzY29zdGFsdXouY29tOk1hcmluYTA0MTIxOTgy");
            jSon.setStatus("POST");
            jSon.setInvoiceType(Inicio.TipoFactura1.getSelectedItem().toString().trim());
            jSon.setInvoiceID(Inicio.NumeroFactura.getText().trim());
            jSon.setInvoiceDate(Inicio.Fecha.getText().trim());
            jSon.setSellerID(Inicio.cif.getText().trim());
            jSon.setCompanyName(Inicio.Empresa.getSelectedItem().toString().trim());
            jSon.setRelatedPartyID("Aqui El Cif Nuestro");
            jSon.setRelatedPartyName(Inicio.clientearea.getText().trim());
            jSon.setText(Inicio.Descripcion.getText().trim());

            Anidado lineas = new Anidado();

            lineas.setBase_imponible(Inicio.Importe.getText().trim().replaceAll("\\.", "").replaceAll("\\,", "."));
            lineas.setTipo_impositivo("21");
            lineas.setCuota_repercutida(Inicio.Iva.getText().trim().replaceAll("\\.", "").replaceAll("\\,", "."));

            jSon.lineas.add(lineas);

            jSon.setImporte_total(Inicio.ImporteTotal.getText().trim().replaceAll("\\.", "").replaceAll("\\,", "."));

            //  jSon.setImporte_total(numeroDecimal);
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            String jsonEjemplo = gson.toJson(jSon);

            String requestBody = jsonEjemplo;
            System.out.println(requestBody);
            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create("https://facturae.irenesolutions.com:8050/Kivu/Taxes/Verifactu/Invoices/Create"))
                    //.header("Authorization", "Bearer " + "vf_test_My3GPdKZWm9O2S+tl3ud2HXJwN29Mxnp56QhuhRLU3M=")
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                    .build();
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            int statusCode = response.statusCode();

            if (statusCode >= 200 && statusCode < 300) {
                //System.out.print("Respuesta exitosa: " + response.body());
                String responseBody = response.body();
                JsonEnvio resp = new JsonEnvio();
                resp = gson.fromJson(responseBody, JsonEnvio.class);
                PrintStream printStream = new PrintStream(new CustomOutputStream(textArea));

                // Redirige System.out y System.err
                System.setOut(printStream);
                System.setErr(printStream);

                //System.out.println(resp.getUrl());
                //System.out.println(resp.getUuid());
                InsertaQr IQr = new InsertaQr();
                IQr.InsertQr("C:\\Facturas\\CodigoQr\\qr.png");
                List lista = new ArrayList();
                String directorio = "C:\\Facturas\\FacturasConQr\\";
                String extension = ".pdf";
                File f = new File(directorio);

                if (f.exists()) { // Directorio existe }
                    File[] ficheros = f.listFiles();
                    for (File fichero1 : ficheros) {
                        String fichero = fichero1.getName();
                        if (fichero.contains(extension)) {
                            lista.add(fichero);
                            File file = new File("C:\\Facturas\\FacturasConQr\\" + fichero);

                            //File file = new File("C:\\Facturas\\FacturasConQr\\103712.pdf");
                            PDDocument document = Loader.loadPDF(file);
                            PrinterJob job = PrinterJob.getPrinterJob();
                            if (job.printDialog() == true) {
                                job.setPageable(new PDFPageable(document));
                                job.print();

                            }
                        }
                    }
                }
                String seleccion = JOptionPane.showInputDialog("Ingrese direccion de correo");  // el icono sera un iterrogante       
                //System.out.println("El usuario ha escrito " + seleccion);
                EnviarMailComplejo e = new EnviarMailComplejo();
                e.Envie(seleccion);
                String st = "Mensaje Enviado \n Muchas Gracias";
                JOptionPane.showMessageDialog(null, st, "MENSAJE ENVIADO!!", 1);

            } else {
                System.err.println("Error: " + statusCode + " - " + response.body());
            }

        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BotonImprimirActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        dispose();
        PDFTextExtractor.pdftext();

    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(PDFTextExtractor::pdftext //new Inicio().setVisible(true);
        );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonImprimir;
    public static javax.swing.JTextField Descripcion;
    public static javax.swing.JComboBox<String> Empresa;
    public static javax.swing.JLabel Fecha;
    public static javax.swing.JLabel Importe;
    public static javax.swing.JLabel ImporteTotal;
    public static javax.swing.JLabel Iva;
    public static javax.swing.JLabel NumeroFactura;
    private javax.swing.JLabel Serie;
    public static javax.swing.JComboBox<String> TipoFactura1;
    public javax.swing.JButton btnActualizar;
    public static javax.swing.JLabel cif;
    public static javax.swing.JLabel clientearea;
    public javax.swing.JLabel clientedireccion;
    public javax.swing.JLabel codigocliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    public javax.swing.JLabel liva;
    public static javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
