
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.gson.GsonBuilder;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpClient;

import java.util.logging.Level;
import java.util.logging.Logger;

import com.google.gson.Gson;
import java.awt.Desktop;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.PrintStream;

import java.text.SimpleDateFormat;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.printing.PDFPageable;

/**
 *
 * @author ivan
 */
public class Inicio extends javax.swing.JFrame {

    public Inicio() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/copiluz.png")).getImage());
        LocalDate fechaActual = LocalDate.now();
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("MM/yyyy");
        String formatoMesYAnio = fechaActual.format(formateador);
        Serie.setText(formatoMesYAnio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clientearea = new javax.swing.JLabel();
        cif = new javax.swing.JLabel();
        codigocliente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        BotonImprimir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        liva = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Importe = new javax.swing.JLabel();
        Iva = new javax.swing.JLabel();
        ImporteTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        NumeroRectificada = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Empresa = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        TipoFactura1 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Descripcion = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumeroFactura = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Serie = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientedireccion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        jLabel6.setText("Importe total");

        jTextField6.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Copiadoras Costaluz Facturas");
        setBackground(new java.awt.Color(0, 0, 102));
        setForeground(java.awt.Color.darkGray);
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Nombre Cliente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 28, -1, -1));

        jLabel8.setText("Nif Cliente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 84, 87, -1));

        jLabel9.setText("Codigo Cliente");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 56, 87, -1));

        jLabel10.setText("direccion");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 118, 87, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 28, -1, -1));

        clientearea.setBackground(new java.awt.Color(0, 0, 0));
        clientearea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clientearea.setText("jLabel11");
        getContentPane().add(clientearea, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 28, 209, -1));

        cif.setBackground(new java.awt.Color(0, 102, 255));
        cif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cif.setText("jLabel11");
        getContentPane().add(cif, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 84, 142, -1));

        codigocliente.setBackground(new java.awt.Color(0, 102, 255));
        codigocliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        codigocliente.setText("jLabel11");
        getContentPane().add(codigocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 56, 209, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        BotonImprimir.setText("Enviar");
        BotonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImprimirActionPerformed(evt);
            }
        });

        jButton2.setText("Listado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(BotonImprimir)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar)
                            .addComponent(BotonImprimir)
                            .addComponent(jButton2))
                        .addGap(16, 16, 16))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 920, 130));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setText("Importe total");

        liva.setText("IVA");

        jLabel3.setText("Importe");

        Importe.setBackground(new java.awt.Color(0, 0, 0));
        Importe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Importe.setText("jLabel11");

        Iva.setBackground(new java.awt.Color(0, 102, 255));
        Iva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Iva.setText("jLabel11");

        ImporteTotal.setBackground(new java.awt.Color(0, 102, 255));
        ImporteTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ImporteTotal.setText("jLabel11");
        ImporteTotal.setVerifyInputWhenFocusTarget(false);

        jLabel15.setText("Numero de Factura Rectificada");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liva, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ImporteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(41, 41, 41)
                        .addComponent(NumeroRectificada, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Importe, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Iva, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Importe))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liva)
                    .addComponent(Iva))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ImporteTotal)
                    .addComponent(jLabel15)
                    .addComponent(NumeroRectificada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 920, 150));

        jPanel8.setBackground(new java.awt.Color(102, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel14.setText("Empresa");

        Empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "copiadoras costaluz", "asitecsur" }));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Fecha");

        Fecha.setBackground(new java.awt.Color(0, 102, 255));
        Fecha.setForeground(new java.awt.Color(0, 51, 204));
        Fecha.setText("jLabel11");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(81, 81, 81)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(Fecha))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Tipo");

        TipoFactura1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F1", "F2", "R1", "R2", "R3", "R4", "R5", "F3", " " }));
        TipoFactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoFactura1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(76, 76, 76)
                    .addComponent(TipoFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(TipoFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Descripcion");

        Descripcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mantenimiento", "Alquiler y mantenimiento", "Alquiler", "Venta Consumibles", "Venta fotocopiadora" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 294, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(3, 3, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Numero Factura");

        NumeroFactura.setBackground(new java.awt.Color(0, 102, 255));
        NumeroFactura.setForeground(new java.awt.Color(0, 51, 204));
        NumeroFactura.setText("jLabel11");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(81, 81, 81)
                .addComponent(NumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(NumeroFactura))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Serie");

        Serie.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(81, 81, 81)
                    .addComponent(Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        clientedireccion.setEditable(false);
        clientedireccion.setBackground(new java.awt.Color(102, 204, 255));
        clientedireccion.setColumns(20);
        clientedireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clientedireccion.setRows(5);
        clientedireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setViewportView(clientedireccion);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 220));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImprimirActionPerformed

        try {

            JsonEnvio jSon = new JsonEnvio();

            String key = "c2F0QGNvcGlhZG9yYXNjb3N0YWx1ei5jb206MTIzNDU=";

            jSon.setServiceKey(key);
            jSon.setStatus("POST");
            jSon.setInvoiceType(Inicio.TipoFactura1.getSelectedItem().toString().trim());

            jSon.setInvoiceID(Inicio.NumeroFactura.getText().trim());
            //  jSon.setInvoiceID("13556");

            Locale espanol = new Locale("es", "ES");
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy", espanol);

            String dateInString = Inicio.Fecha.getText();
            Date date = formatter.parse(dateInString);
            jSon.setInvoiceDate(date);

            String Combo = Inicio.Empresa.getSelectedItem().toString().trim();
            if ("copiadoras costaluz".equals(Combo)) {

                String Cif = "B21217385";
                jSon.setSellerID(Cif);
            }
            if ("asitecsur".equals(Combo)) {

                String Cif = "B21590385";
                jSon.setSellerID(Cif);
            }
            // jSon.setSellerID(Cif);
            jSon.setCompanyName(Inicio.Empresa.getSelectedItem().toString().trim());
            jSon.setRelatedPartyID(Inicio.cif.getText().trim());
            jSon.setRelatedPartyName(Inicio.clientearea.getText().trim());
            jSon.setText(Inicio.Descripcion.getSelectedItem().toString().trim());

            Anidado TaxItems = new Anidado();

            TaxItems.setTaxScheme("01");
            // TaxItems.setTaxType(Inicio.Importe.getText().trim().replaceAll("\\.", "").replaceAll("\\,", "."));
            TaxItems.setTaxType("S1");
            TaxItems.setTaxRate("21");
            TaxItems.setTaxBase(Inicio.Importe.getText().trim().replaceAll("\\.", "").replaceAll("\\,", "."));
            TaxItems.setTaxAmount(Inicio.Iva.getText().trim().replaceAll("\\.", "").replaceAll("\\,", "."));

            jSon.TaxItems.add(TaxItems);

           // String rectificaciones = Inicio.TipoFactura1.getSelectedItem().toString();
            if ("R1".equals(Inicio.TipoFactura1.getSelectedItem().toString())) {
                Rectificadas Rectification = new Rectificadas();
                Rectification.setInvoiceID(Inicio.NumeroRectificada.getText().trim());

                Rectification.setInvoiceDate(date);
                jSon.RectificationItems.add(Rectification);
            }

            // jSon.setImporte_total(Inicio.ImporteTotal.getText().trim().replaceAll("\\.", "").replaceAll("\\,", "."));
            //  jSon.setImporte_total(numeroDecimal);
            Gson gson = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create();
            String jsonEjemplo = gson.toJson(jSon);

            String requestBody = jsonEjemplo;
            System.out.println(requestBody);
            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create("https://facturae.irenesolutions.com:8050/Kivu/Taxes/Verifactu/Invoices/Create"))
                    //.header("Authorization", "Bearer " + "vf_test_My3GPdKZWm9O2S+tl3ud2HXJwN29Mxnp56QhuhRLU3M=")
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                    .build();
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            int statusCode = response.statusCode();

            if (statusCode >= 200 && statusCode < 300) {
                //System.out.print("Respuesta exitosa: " + response.body());
                String responseBody = response.body();
                JsonEnvio resp = new JsonEnvio();
                resp = gson.fromJson(responseBody, JsonEnvio.class);
                PrintStream printStream = new PrintStream(new CustomOutputStream(textArea));
                // Thread.sleep(5000);
                // Redirige System.out y System.err
                System.setOut(printStream);
                System.setErr(printStream);
                ObjectMapper objectMapper = new ObjectMapper();
                Map<String, Object> objetoDinamico = objectMapper.readValue(response.body(), HashMap.class);
                Gson gson1 = new Gson();
                String json = gson.toJson(objetoDinamico.get("Return"));

                response resp1 = gson1.fromJson(json, response.class);
                Decoder decoder = new Decoder();
                decoder.Decoder(resp1.QrCode.trim());

                //System.out.println(resp.getUrl());
                //System.out.println(resp.getUuid());
                InsertaQr IQr = new InsertaQr();
                IQr.InsertQr("C:\\Facturas\\CodigoQr\\qr.png", "C:\\Facturas\\CodigoQr\\cuadro.png");
                //  List lista = new ArrayList();
                String directorio = "C:\\Facturas\\FacturasConQr\\";
                String extension = ".pdf";
                File f = new File(directorio);

                if (f.exists()) { // Directorio existe }
                    File[] ficheros = f.listFiles();
                    for (File fichero1 : ficheros) {
                        String fichero = fichero1.getName();
                        if (fichero.contains(Inicio.NumeroFactura.getText().trim())) {
                            // lista.add(fichero);
                            File file = new File("C:\\Facturas\\FacturasConQr\\" + fichero);

                            //File file = new File("C:\\Facturas\\FacturasConQr\\103712.pdf");
                            PDDocument document = Loader.loadPDF(file);
                            PrinterJob job = PrinterJob.getPrinterJob();
                            if (job.printDialog() == true) {
                                job.setPageable(new PDFPageable(document));
                                job.print();

                            }
                        }
                    }
                }
                /////////////////////desde aqui Hace la consulta postgres//////////////////////////
                ConsultaPostgre consulta = new ConsultaPostgre();
                 String dato = codigocliente.getText();
               // String dato = "709";
                consulta.test(dato);

                System.out.println(dato);
                // System.out.println(consulta.test);
                // Print(directorio + Inicio.NumeroFactura.getText().trim() + extension);
                String seleccion = JOptionPane.showInputDialog("Ingrese direccion de correo",cif.getText());
                // el icono sera un iterrogante       

                EnviarMailComplejo e = new EnviarMailComplejo();
                e.Envie(seleccion);
                String st = "Mensaje Enviado \n Muchas Gracias";
                JOptionPane.showMessageDialog(null, st, "MENSAJE ENVIADO!!", 1);
                //DESDE AQUI BORRA EL QR
                String nombreArchivo = "C:\\Facturas\\CodigoQr\\qr.png"; // Ruta del archivo a borrar
                File archivo = new File(nombreArchivo);
                if (archivo.exists()) {
                    boolean eliminado = archivo.delete();
                    if (eliminado) {
                        JOptionPane.showMessageDialog(null, "Codigo QR eliminado",
                                "INFORMATION_MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                        System.out.println("El archivo " + nombreArchivo + " se eliminó correctamente.");
                    } else {
                        System.out.println("No se pudo eliminar el archivo " + nombreArchivo);
                    }
                } else {
                    System.out.println("El archivo " + nombreArchivo + " no existe.");
                }
                //DESDE AQUI BORRA LA FACTURA ANTIGUA
                String rutaCarpeta = "C:\\Facturas\\";
                File carpeta = new File(rutaCarpeta);

                // Obtiene todos los archivos y directorios dentro de la carpeta
                File[] archivos = carpeta.listFiles();

                if (archivos != null) {
                    for (File archivo1 : archivos) {
                        // Verifica si el archivo es un archivo regular y tiene la extensión .pdf
                        if (archivo1.isFile() && archivo1.getName().toLowerCase().endsWith(".pdf")) {
                            // Elimina el archivo y comprueba si se eliminó correctamente
                            if (archivo1.delete()) {
                                System.out.println("Se elimino el archivo: " + archivo1.getName());
                            } else {
                                System.out.println("No se pudo eliminar el archivo: " + archivo1.getName());
                            }
                        }
                    }
                } else {
                    System.out.println("No se pudo listar el contenido de la carpeta: " + rutaCarpeta);
                }

            } else {
                System.err.println("Error: " + statusCode + " - " + response.body());
            }

        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BotonImprimirActionPerformed
    public void Print(String ruta) {
        Desktop print = Desktop.getDesktop();
        try {
            File archivoAImprimir = new File(ruta);
            print.print(archivoAImprimir);
        } catch (IOException ex) {
        }

    }
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        dispose();
        PDFTextExtractor.pdftext();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Consultas.Listado listado = new Consultas.Listado();
        listado.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TipoFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoFactura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoFactura1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(PDFTextExtractor::pdftext //new Inicio().setVisible(true);
        );
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonImprimir;
    public static javax.swing.JComboBox<String> Descripcion;
    public static javax.swing.JComboBox<String> Empresa;
    public static javax.swing.JLabel Fecha;
    public static javax.swing.JLabel Importe;
    public static javax.swing.JLabel ImporteTotal;
    public static javax.swing.JLabel Iva;
    public static javax.swing.JLabel NumeroFactura;
    public static javax.swing.JTextField NumeroRectificada;
    private javax.swing.JLabel Serie;
    public static javax.swing.JComboBox<String> TipoFactura1;
    public javax.swing.JButton btnActualizar;
    public static javax.swing.JLabel cif;
    public static javax.swing.JLabel clientearea;
    public static javax.swing.JTextArea clientedireccion;
    public javax.swing.JLabel codigocliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField6;
    public javax.swing.JLabel liva;
    public static javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

}
